### PR TITLE
Rickventura patch 1

### PR DESCRIPTION
**Pull request by Rickventura**
A minor change in TITagitstandard.c function to make TITagitstandardFlipUid more efficient.
Not being familiar with github, I am not sure about the effect of this pull request from bosb:iso15693_base. Please forgive my ignorance.

### CODE REVIEW

**Comment by bosb** [comment]
When I saw the diff, the change to the readme reminded me to pull the master changes from emsec.

The diff to TITagitstandard.c looked like every line changed, that is usually a indicator the lineending is changed, this repository is mostly with unix lineending, while your file looks like dos lineends.
Can you change that in your editor? On macosx/linux there is dos2unix as comandline tool available.
Then the diff here better indicates the real changes.

While I pulled the master we ended here also in merge conflicts, these I do not jet understand, why they happened. When you want to push now changes to this Pullrequest, you might end in needing to solve these conflicts....Lets see, maybe more learning for you, sorry.

**Comment by bosb** [comment]
@Rickventura please use the 'resolve conflicts' button, and try to edit the file to your result.

**Comment by Rickventura** [comment]
I've never attempted this sort of changes. I would only replace the function  TITagitstandardFlipUid.
what should I do with those charactes <<<<<<<, =======, >>>>>>> that I see in the "conflicts file"?

**Comment by bosb** [comment]
https://help.github.com/articles/resolving-a-merge-conflict-on-github/

They indicate the conflict that would happen, if I accept the pull request.
the part above the ============ is from your file
the part below is how this part of the file looks like in my bosb branch file.
I think it looks different, because I took changes from ceres-c, which might not be in your file....

So decide which parts you want and remove the rest. Let's see what happens :-)

**Comment by Rickventura** [comment]
@bosb I think I made it. Thanks for helping me out.

**Comment by Rickventura** [comment]
I am using linux. However I had adjusted the indentation of those lines.
Maybe that's the reason.

Il giorno lun 12 nov 2018, 12:54 Thorsten <notifications@github.com> ha
scritto:

**Pull request merged**
